[2025-01-24T18:50:34.994+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:50:33.124447+00:00 [queued]>
[2025-01-24T18:50:35.023+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:50:33.124447+00:00 [queued]>
[2025-01-24T18:50:35.023+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-24T18:50:35.040+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2025-01-24 18:50:33.124447+00:00
[2025-01-24T18:50:35.054+0000] {standard_task_runner.py:57} INFO - Started process 277 to run task
[2025-01-24T18:50:35.061+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_to_redshift_copy_command', 'load_data_to_redshift', 'manual__2025-01-24T18:50:33.124447+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/load_user.py', '--cfg-path', '/tmp/tmpbnus29nj']
[2025-01-24T18:50:35.065+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask load_data_to_redshift
[2025-01-24T18:50:35.132+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-24T18:50:35.169+0000] {task_command.py:415} INFO - Running <TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:50:33.124447+00:00 [running]> on host 423700a35b1c
[2025-01-24T18:50:35.238+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_redshift_copy_command' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T18:50:33.124447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T18:50:33.124447+00:00'
[2025-01-24T18:50:35.273+0000] {base.py:73} INFO - Using connection ID 'redshift_default' for task execution.
[2025-01-24T18:50:36.655+0000] {sql.py:418} INFO - Running statement: 
    COPY public.user_details
    FROM 's3://datalakepax8/external/user_data.json'
    IAM_ROLE 'arn:aws:iam::654654432597:role/s3-access-to-redshift'  
    FORMAT AS JSON 'auto'
    IGNOREHEADER 1;  
    , parameters: None
[2025-01-24T18:50:43.926+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-24T18:50:43.964+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_redshift_copy_command, task_id=load_data_to_redshift, execution_date=20250124T185033, start_date=20250124T185035, end_date=20250124T185043
[2025-01-24T18:50:44.020+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-24T18:50:44.057+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
